name: PortainerProxy
version: 1.0.2
slug: sproxy
description: HA ingress
url: https://github.com/
image: ghcr.io/maxwinterstein/homeassistant-addon-octoprint-proxy-{arch}
ingress: true
ingress_port: 80
panel_title: Portainer
panel_icon: mdi:docker
arch:
  - armv7
  - aarch64
  - amd64
init: false
options:
  host: host
  port: "443"
  ssl:
    enabled: true
    verify: false
schema:
  host: str
  port: port
  ssl:
    enabled: bool
    verify: bool
    hassio_api: true
hassio_role: supervisor
services:
  - mysql:want
  - mqtt:want
homeassistant_api: true
host_network: true
uart: true
usb: true
gpio: true
audio: true
apparmor: false
host_dbus: true
docker_api: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
devices:
  - /dev/mem
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - media:rw
  - share:rw
  - backup:rw
journald: true